<script setup>
import Markdown from "vue3-markdown-it"; /* PartiallyEnd: #3632/scriptSetup.vue */

import AppLayout from "@/Layouts/AppLayout.vue";
const terms = `# Terms Of Use

**Last Updated: February 1st, 2025**

## IMPORTANT NOTICE: READ CAREFULLY – NOT A TRADING PLATFORM, NO CUSTODY, EXTREME RISK OF LOSS.

**Sharkpump.io IS NOT A TRADING PLATFORM, BROKERAGE, OR INVESTMENT SERVICE.** We are solely a technology provider offering **transaction templates.** We **do not provide custody** of digital assets, operate an exchange, or offer any form of investment or financial advice. Digital assets showcased or discussed on this Site are **user-created, highly speculative, and carry an extreme risk of total financial loss.** You could lose your entire investment.

**BY USING THIS SITE, YOU EXPRESSLY ACKNOWLEDGE, UNDERSTAND, AND AGREE TO THE INHERENT AND SUBSTANTIAL RISKS, LIMITATIONS, AND DISCLAIMERS DETAILED BELOW.** This document is not legal or financial advice. **Consult professional legal and financial counsel before using this Site or engaging in any digital asset transactions.**

## 1. Introduction

Welcome to Sharkpump.io (the "Site"), an informational interface and technology tool providing blockchain transaction templates. Sharkpump.io (referred to as "we," "our," or "us") operates as a non-custodial service, exclusively offering tools to help users create transaction data. We do not provide custody, execute trades, or facilitate exchanges for profit. Instead, we simply offer a formatted interface to assist users in generating transaction data, which they may independently choose to broadcast to a blockchain network using their own external cryptocurrency wallets.

These Terms of Use ("Terms") govern your access to and use of the Site and any related services and features provided (collectively, the "Services"). Please read these Terms carefully and completely. By accessing or using our Site, you confirm that you have read, understood, and unconditionally agree to be bound by these Terms in their entirety. If you do not agree, you must not access or use the Site.

## 2. No Custody, No Brokerage, No Exchange – Purely a Transaction Templating Tool

### 2.1. Non-Custodial Interface – Absolute User Control and Responsibility

We operate a strictly non-custodial technology solution. We never hold, manage, control, or have access to your digital assets, private keys, or wallet credentials. Your digital assets remain solely under your control at all times.

All blockchain transactions you submit are initiated, authorized, and executed solely by you, independently through your own third-party digital wallet or smart contract interface. You bear exclusive and absolute responsibility for the security, access, and management of your private keys, digital wallets, and all digital assets held therein.

### 2.2 No Execution or Brokerage – Not a Financial or Intermediary Service

Sharkpump.io is not a registered or regulated entity and does not operate as a broker, dealer, exchange, investment adviser, money transmitter, payment processor, or any other form of financial intermediary.

We do not match buyers and sellers, operate order books, facilitate trade execution, or handle any aspect of transaction settlement or clearing.

Sharkpump.io provides no investment advice, financial recommendations, endorsements, or solicitations regarding any digital asset, token, or transaction. Information displayed on the Site is for informational purposes only and should not be construed as investment advice.

Any transaction data generated by the Site uses templates and is initiated and broadcast solely by you. You, and you alone, are solely responsible for deciding whether to finalize and broadcast such transactions to any blockchain. We play no role in transaction execution or settlement.

## 3. Transaction Templates – User-Driven and User-Verified

### 3.1 Transaction Templates – Convenience and Formatting Assistance Only

The Site provides user-friendly interfaces and pre-designed "transaction templates" (e.g., for assisting in creating new tokens, providing liquidity to decentralized exchanges, or interacting with smart contracts). These templates are intended solely to assist users in formatting blockchain transaction parameters and are provided for convenience only.

Crucially, you remain fully and exclusively responsible for all aspects of any transaction you choose to initiate, including but not limited to: independently verifying the accuracy and completeness of all transaction parameters, ensuring the sufficiency of blockchain network fees (gas fees), and confirming full compliance with all applicable laws and regulations before broadcasting any transaction.

### 3.2 User Due Diligence – Your Essential Obligation to Investigate and Verify

Prior to using the Site to format any transaction, you acknowledge and agree that you must conduct your own thorough, independent, and informed due diligence regarding any digital asset, token creation, liquidity provision, smart contract interaction, or other on-chain transaction. This includes, but is not limited to, researching the underlying technology, smart contract code, tokenomics, potential risks, and legal and regulatory implications.

By using the Site, you explicitly acknowledge and agree that Sharkpump.io provides no due diligence, verification, or vetting of any kind and that we have not verified the legitimacy, authenticity, security, safety, or quality of any smart contract, digital asset, or project you interact with through the Site. All such verification and risk assessment is solely your responsibility.

### 3.3 No Endorsement – Informational Display Without Warranty

Any references to, mentions of, or display of third-party protocols, tokens, digital assets, services, projects, or entities on the Site are provided solely for informational and convenience purposes and do not, under any circumstances, constitute an endorsement, recommendation, sponsorship, promotion, or warranty of any kind by Sharkpump.io.

The display of logos, token symbols, price data, market capitalization information, or other data on the Site is intended solely for user convenience in formatting transactions and does not imply any opinion, endorsement, validation, or guarantee of accuracy, reliability, or legitimacy by Sharkpump.io. We provide no representations or warranties regarding the accuracy, completeness, or timeliness of any data displayed on the Site, which is sourced from publicly available blockchain data and may be subject to errors, delays, and manipulation.

## 4. Assumption of Risk – You Must Understand and Accept Extreme Dangers

### 4.1 Blockchain and Cryptocurrency Risks – Inherent, Substantial, and Potentially Devastating

You expressly acknowledge, understand, and agree that engaging with digital assets and blockchain transactions, particularly memecoins and tokens created and traded on platforms like the Site, is inherently speculative, extraordinarily risky, and carries a significant and ever-present risk of substantial and potentially total financial loss. These risks include, but are not limited to:

* **Extreme Market Volatility and Price Swings**: Digital asset markets are characterized by extreme volatility, and prices for memecoins and tokens created and traded using the Site can fluctuate wildly and unpredictably, potentially resulting in rapid and complete loss of funds.
* **Total Loss of Funds**: You acknowledge and accept that you could lose all cryptocurrency and digital assets used in transactions initiated through the Site. The value of memecoins and tokens can rapidly decline to zero.
* **Smart Contract Risks and Exploitable Vulnerabilities**: Smart contracts are complex computer code and are known to be vulnerable to coding errors, bugs, security flaws, and exploits. These vulnerabilities can be exploited by malicious actors, potentially leading to the theft or irreversible loss of your digital assets.
* **Rug Pull Scams and Fraudulent Schemes**: Memecoins and tokens, especially those created on open platforms, are highly susceptible to "rug pull" scams, pump-and-dump schemes, and other fraudulent activities. Creators or insiders may manipulate token prices and then abscond with user funds, leaving other users with worthless tokens and devastating losses. Sharkpump.io provides absolutely no protection against such scams.
* **Exchange and Custodial Platform Risks**: Digital asset exchanges and wallet providers, including those you may choose to use to interact with the Site and manage your digital assets, are inherently risky and vulnerable to closure due to fraud, operational failure, security breaches, market manipulation, and regulatory actions. Any funds or digital assets held on such platforms are at risk of loss, theft, or inaccessibility.
* **Illiquidity and Market Manipulation**: Many digital assets, particularly newly created memecoins and tokens, may have severely limited or no liquidity. This means you may be unable to sell or trade them at desired prices or at all, especially during periods of market downturn or panic selling. Market prices for illiquid digital assets can be easily manipulated, and information displayed on the Site regarding prices may not reflect actual trading prices or available liquidity.
* **Legal and Regulatory Uncertainty and Risk**: The legal and regulatory status of digital assets, including memecoins and tokens, is highly uncertain and subject to rapid change. Governmental authorities worldwide are actively examining and regulating the digital asset space. Future regulations may drastically alter or negatively impact the legality, functionality, and value of digital assets, and may restrict or prohibit the operation of platforms like the Site.
* **Private Key Security and Irreversible Loss**: Control of digital assets is exclusively dependent on the possession of private keys. Loss, theft, compromise, or destruction of your private keys will inevitably and irreversibly result in the permanent loss of your digital assets. Sharkpump.io has no access to or control over your private keys and cannot recover them under any circumstances if lost.
* **Technology and Infrastructure Risks**: Blockchain technology, smart contracts, decentralized systems, and the Site itself are experimental and rely on complex and unproven technologies. These systems are subject to technical failures, software bugs, network congestion, security vulnerabilities, and unforeseen operational risks that could lead to service disruptions, data loss, and financial losses.
* **Force Majeure Events and Unforeseen Circumstances**: The digital asset ecosystem and the Site are vulnerable to force majeure events and unforeseen circumstances that are beyond our control, including but not limited to acts of God, natural disasters, war, terrorism, cyberattacks, pandemics, governmental actions, and regulatory changes. These events can cause significant disruptions, market instability, and loss of value.

### 4.2 No Guarantees, No Promises of Profit, No Investment Advice – You Are Your Own Financial Advisor

Sharkpump.io makes no guarantees, promises, or representations of any kind regarding the Site, the Services, or any digital assets accessed or created through the Site. We do not guarantee that using the Site will result in financial gains, profits, successful token launches, or any other positive outcome.

Sharkpump.io explicitly disclaims any and all responsibility for your financial outcomes and provides no financial, investment, legal, tax, or other professional advice. Information provided on the Site, including price data, educational content, and transaction templates, is for informational purposes only and should never be construed as advice or a recommendation to engage in any transaction or investment strategy.

You acknowledge and agree that you are solely responsible for all of your investment decisions and financial activities related to digital assets and blockchain transactions. You must conduct your own independent research, seek advice from qualified financial and legal professionals, and carefully consider your own risk tolerance and financial circumstances before using the Site or engaging in any digital asset transactions. Never invest more than you can afford to lose entirely.

### 4.3 Experimental Technology and "Beta" Nature – Expect Imperfections and Risks

You acknowledge and agree that the Site and Services are based on rapidly evolving, experimental, and "beta" stage blockchain technology and software. As such, you understand that the Site and Services may contain errors, bugs, inaccuracies, unexpected behavior, and security vulnerabilities.

You explicitly agree that your use of the Site and any experimental features is entirely at your own risk. We make no warranties or representations regarding the uptime, performance, accuracy, security, or reliability of the Site, Services, or any experimental features. You assume all risks associated with using experimental technology and acknowledge that disruptions, errors, and unexpected outcomes are possible.

## 5. User Representations and Warranties – Your Binding Commitments to Us

By accessing and using the Site, you represent and warrant to Sharkpump.io that, continuously and at all times:

* **Age and Legal Capacity**: You are of legal age in your jurisdiction (at least 18 years old) and possess the full legal right, power, and capacity to enter into these Terms and to fully perform your obligations hereunder.
* **Risk Comprehension and Acceptance**: You have carefully read, fully understand, and knowingly and voluntarily accept the substantial and inherent risks associated with blockchain technology, digital assets, and the use of the Site, as detailed extensively in Section 4 of these Terms.
* **Independent and Informed Decision-Making**: You are accessing and using the Site and making all decisions regarding digital assets and transactions solely on your own behalf, based on your own independent judgment, thorough research, and informed consent. You are not relying on Sharkpump.io for any advice, recommendations, endorsements, or guarantees of any kind.
* **Sufficient Knowledge and Expertise**: You possess sufficient knowledge, experience, and understanding of blockchain technology, cryptography, digital assets, smart contracts, and financial markets to responsibly use the Site and Services and to fully assess and assume the risks involved in any transactions you undertake.
* **Lawful and Ethical Use and Intent**: You will utilize the Site and Services strictly for lawful and ethically appropriate purposes and transactions. You will not use the Site for any illegal, fraudulent, manipulative, unethical, or harmful activity, or in any manner that violates these Terms or any applicable laws or regulations, or that harms or defrauds others.
* **No Expectation of Guaranteed Profit or Financial Gain**: You understand, acknowledge, and agree that Sharkpump.io makes no promises or guarantees of profit, financial gain, or any specific financial outcome, and you are not using the Site with any such expectation of guaranteed returns or financial success.
* **Regulatory and Legal Compliance**: Your access to and use of the Site, and all related blockchain activities, are and will continue to be in full compliance with all applicable laws, rules, and regulations in your jurisdiction(s), including but not limited to securities laws, commodities laws, tax laws, anti-money laundering laws, consumer protection laws, and data privacy laws.
* **Accuracy and Truthfulness of Information**: All information you provide to Sharkpump.io, whether directly or indirectly, is truthful, accurate, complete, and not misleading in any respect.
* **No Location in Restricted Jurisdictions**: You are not physically located in, under the control of, and are not a national or resident of any country or region that Sharkpump.io has designated as a Restricted Jurisdiction (as defined and updated from time to time on the Site).
* **Transaction Verification Responsibility**: You understand and agree that, before signing and broadcasting any transaction using your digital wallet, you are solely and exclusively responsible for independently verifying all transaction parameters, including but not limited to recipient addresses, token amounts, smart contract interactions, and blockchain network fees. You will not rely solely on the Site's display of transaction parameters and will perform your own thorough verification.

## 6. Fees and Operation

Sharkpump.io is currently operated as a community-focused initiative. Sharkpump.io collects fees for the use of the Site or Services. Sharkpump.io reserves the right to modify fees in the future. Should any fee changes be implemented, they will be clearly and transparently disclosed to users at [https://Sharkpump.io/fees](https://sharkpump.io/fees).

You remain solely and exclusively responsible for paying all blockchain network fees (gas fees) associated with any transactions you choose to submit through the Site. These blockchain network fees are paid directly to the relevant blockchain network validators or miners and are entirely outside of Sharkpump.io's control or benefit. Sharkpump.io receives no portion of blockchain network fees.

## 7. No Warranties; Full Disclaimer of Liability – You Assume All Risks

### 7.1 No Warranties – Site and Services Provided "As Is"

THE SITE AND SERVICES, INCLUDING ALL CONTENT, SOFTWARE, TRANSACTION TEMPLATES, DATA, AND FUNCTIONALITY, ARE PROVIDED STRICTLY ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SHARKPUMP.IO AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AND AGENTS, HEREBY EXPRESSLY DISCLAIM ALL WARRANTIES (EXPRESS, IMPLIED, OR STATUTORY) REGARDING THE SITE AND SERVICES, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, RELIABILITY, SECURITY, UPTIME, OR FREEDOM FROM ERRORS, BUGS, VIRUSES, OR OTHER HARMFUL COMPONENTS. WE MAKE NO WARRANTY THAT THE SITE OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED.

### 7.2 Maximum Limitation of Liability – Nominal Cap to the Extent Permitted by Law

TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SHARKPUMP.IO, NOR ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, OR AGENTS, BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF GOODWILL, LOSS OF DATA, LOSS OF OPPORTUNITY, BUSINESS INTERRUPTION, COMPUTER FAILURE OR MALFUNCTION, OR ANY OTHER INTANGIBLE OR ECONOMIC LOSSES), ARISING OUT OF OR IN ANY WAY CONNECTED WITH THESE TERMS, THE SITE, THE SERVICES, OR YOUR USE THEREOF, OR ANY TRANSACTIONS INITIATED OR FACILITATED THROUGH THE SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF SHARKPUMP.IO HAS BEEN EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES, AND REGARDLESS OF WHETHER SUCH DAMAGES OR LOSSES WERE FORESEEABLE OR REASONABLY FORESEEABLE.

### 7.3 Zero Liability Policy

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SHARKPUMP.IO AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AND AGENTS SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY CLAIMS, DAMAGES, LOSSES, OR LIABILITIES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, THE SITE, OR YOUR USE OF THE SERVICES.

SHARKPUMP.IO DISCLAIMS ALL RESPONSIBILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR OTHER INTANGIBLE LOSSES, REGARDLESS OF THE FORM OF ACTION OR LEGAL THEORY (WHETHER IN CONTRACT, TORT, STATUTE, OR OTHERWISE), EVEN IF SHARKPUMP.IO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

BY USING THE SITE OR SERVICES, YOU EXPRESSLY AGREE THAT YOU ASSUME ALL RISK AND THAT SHARKPUMP.IO SHALL NOT BE HELD LIABLE FOR ANY DAMAGES OR LOSSES RESULTING FROM YOUR USE OF THE PLATFORM.

### 7.4 No Liability for Digital Asset Transactions, Blockchain Events, or User Actions

Sharkpump.io explicitly disclaims any and all responsibility and liability for:

* Any blockchain transactions you submit or attempt to submit through the Site, including transaction failures, delays, errors, or losses.
* The outcomes, success, failure, profitability, or loss of value of any digital asset you create, hold, or trade.
* Market volatility, price fluctuations, or any financial losses incurred through trading or holding digital assets.
* Technical failures, security breaches, vulnerabilities, or operational issues of blockchain networks, smart contracts, digital wallets, exchanges, or any third-party services you choose to utilize.
* Network-level issues, including but not limited to blockchain forks, reorganizations, 51% attacks, or consensus failures.
* The actions, omissions, conduct, or misrepresentations of other users of the Site or blockchain networks, including but not limited to fraudulent schemes, rug pulls, scams, or market manipulation.
* The accuracy, completeness, or reliability of any data or information displayed on the Site, including price data, market capitalization, or other blockchain data.

## 8. Indemnification – You Agree to Protect and Hold Us Harmless

You agree to indemnify, defend, and hold harmless Sharkpump.io, its affiliates, officers, directors, employees, contractors, agents, licensors, and suppliers (the "Indemnified Parties") from and against any and all claims, demands, actions, liabilities, damages, losses, judgments, awards, penalties, fines, costs, or expenses (including reasonable attorneys' fees) (collectively, "Losses"), arising directly or indirectly from: (a) your access to or use of the Site or Services; (b) your breach or violation of these Terms; (c) any transaction you initiate, conduct, or facilitate using the Site or Services; (d) any digital asset you create, hold, provide liquidity for, purchase, sell, or trade using the Site or Services; (e) your violation of any applicable law, rule, regulation, or third-party right; (f) any User Materials you submit or transmit through the Site; (g) your negligence, gross negligence, willful misconduct, or fraud; or (h) any dispute you have with any other user of the Site or any third party. You will cooperate fully in the defense of any such claim as reasonably requested by the Indemnified Parties. Sharkpump.io reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you shall not in any event settle any matter without Sharkpump.io's written consent.

## 9. Arbitration and Class Action Waiver – Individual Dispute Resolution Only

### 9.1 Mandatory Binding Arbitration – Exclusive Dispute Resolution Mechanism

Any dispute, claim, or controversy arising out of or relating to these Terms or the Services, or the breach, termination, enforcement, interpretation, or validity thereof (collectively, "Disputes"), shall be resolved by final and binding arbitration administered by the London Court of International Arbitration (the "LCIA") in accordance with the LCIA Rules for the time being in force, which rules are deemed to be incorporated by reference into this clause. The arbitration shall be conducted by a single arbitrator mutually agreed upon by the parties, or if the parties cannot agree, appointed in accordance with the LCIA Rules. The seat and location of the arbitration shall be London, England. The language of the arbitration shall be English. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The decision of the arbitrator shall be final and binding on both parties and enforceable in any court of competent jurisdiction. "Disputes" for purposes of this Section 9 includes any dispute, claim, or controversy of any kind, whether based in contract, tort, statute, equity, or any other legal theory, and whether arising before, during, or after the termination of these Terms.

### 9.2 Class Action Waiver – You Waive Right to Class or Representative Lawsuits

YOU AND SHARKPUMP.IO HEREBY EXPRESSLY AND IRREVOCABLY WAIVE ANY AND ALL RIGHTS TO BRING, MAINTAIN, OR PARTICIPATE IN ANY CLASS ACTION, COLLECTIVE ACTION, REPRESENTATIVE ACTION, OR PRIVATE ATTORNEY GENERAL ACTION, OR CLASS-WIDE ARBITRATION, IN CONNECTION WITH ANY DISPUTE ARISING UNDER OR RELATING TO THESE TERMS, THE SITE, OR THE SERVICES. ALL CLAIMS, DEMANDS, AND CAUSES OF ACTION MUST BE BROUGHT IN YOUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, OR REPRESENTATIVE PROCEEDING. THE ARBITRATOR SHALL HAVE NO POWER OR AUTHORITY TO CONDUCT CLASS ARBITRATION OR AWARD CLASS-WIDE RELIEF. YOU ACKNOWLEDGE THAT THIS CLASS ACTION WAIVER IS A MATERIAL AND ESSENTIAL PART OF THESE TERMS AND THAT YOU ARE KNOWINGLY AND VOLUNTARILY WAIVING YOUR RIGHT TO PARTICIPATE IN CLASS ACTIONS.

## 10. User Conduct and Responsible Use – Ethical and Lawful Activities Only

### 10.1 Prohibited User Conduct – You Must Not Engage in Unlawful, Harmful, or Unethical Activities

You explicitly agree, represent, and warrant that you will not use the Site or any related Services in any manner that:

* **Violates Laws and Regulations**: Violates or promotes the violation of any applicable law, rule, regulation, or governmental decree, including but not limited to securities, commodities, anti-money laundering, sanctions, export control, tax, consumer protection, intellectual property, or privacy laws.
* **Fraudulent, Scam, and Manipulative Activities**: Involves, promotes, or facilitates fraud, scams, deceptive practices, market manipulation, pump-and-dump schemes, rug pulls, or other unlawful or unethical financial schemes, including distributing malicious or fraudulent smart contracts or engaging in deceptive marketing.
* **Harassment, Abuse, and Infringement of Rights**: Harasses, abuses, threatens, defames, or impersonates any person or entity, or infringes upon the legal rights of others, including intellectual property, privacy, publicity, or contractual rights.
* **Harmful, Offensive, and Illegal Content**: Distributes, transmits, or promotes access to any content that is illegal, harmful, offensive, or objectionable, including but not limited to defamatory, obscene, pornographic, sexually explicit, discriminatory, hateful, or violent content.
* **Unauthorized Access and Security Breaches**: Attempts to gain unauthorized access to the Site, user accounts, computer systems, networks, or data, or to circumvent any security measures or access controls.
* **Interference with Site Functionality**: Interferes with, disrupts, damages, or impairs the proper functioning or security of the Site or Services, including transmitting viruses, malware, or engaging in denial-of-service attacks, spamming, or other disruptive activities.
* **Automated Abuse and Excessive Usage**: Uses automated systems, bots, scrapers, or scripts to access the Site or Services in a manner that violates these Terms, exceeds reasonable usage limits, or burdens the Site's infrastructure.
* **Misleading Statements and Misrepresentations**: Makes misleading, false, deceptive, or inaccurate statements or claims about digital assets, the Site, the Services, or Sharkpump.io.
* **Use by Minors**: Uses the Site or Services if you are under the age of 18 (or the age of legal majority in your jurisdiction).
* **Circumvention of Restrictions**: Attempts to circumvent, bypass, or disable any security features, access controls, geographic restrictions, IP blocking, or other protective measures implemented by Sharkpump.io.

### 10.2 Reporting Abuse – Community Responsibility for Site Integrity

If you suspect or become aware of any suspicious, unethical, harmful, or unlawful activity or content on the Site, or if you believe that any user-generated content or transaction template is intended to facilitate fraud, market manipulation, or other illicit conduct, you are strongly encouraged to promptly report such activity to Sharkpump.io by emailing us at: [Abuse Reporting Email Address]. Your vigilance and responsible reporting are essential to maintaining the integrity and safety of the Site and the broader community.

### 10.3 Automated Anti-Abuse and Risk Detection Systems – Algorithmic Safety Measures

Sharkpump.io may, but is not obligated to, employ automated systems, algorithms, and machine learning techniques to detect potentially harmful transaction patterns, suspicious user behavior, and content that may violate these Terms or pose risks to users. If these automated systems flag your activity or content, the Site may, without prior notice or liability to you, take actions including but not limited to: displaying warning messages, requiring additional verification steps, temporarily or permanently limiting your ability to use certain features, restricting or suspending your access, or removing or disabling user-generated content or transaction templates. You acknowledge and agree that these automated protective measures are implemented for general safety and risk mitigation and create no obligation on our part to monitor all user activity, prevent all harmful conduct, or guarantee the detection or prevention of all risks. We are not liable for any errors, inaccuracies, or limitations in the functionality or effectiveness of these automated systems, or for any actions taken or not taken based on their output.

### 10.4 Ethical Use Guidelines – Promoting Responsible Blockchain Interaction

While Sharkpump.io is not responsible for policing user behavior, we strongly encourage all users to utilize the Site and Services in a responsible, ethical, and lawful manner, consistent with the principles of good faith and community respect. You agree to use the Site only for ethically appropriate transactions that do not exploit vulnerabilities in blockchain systems, target vulnerable or unsophisticated users, promote harmful or misleading content, or otherwise engage in activities inconsistent with the responsible and beneficial development and use of blockchain technology.`;
</script>

<template>
	<AppLayout>
		<div class="min-h-screen bg-gray900">
			<div class="max-w-6xl mx-auto px-4 py-8">
				<div
					class="prose markdown-content dark:prose-invert text-white max-w-none"
				>
					<Markdown class="gap-3" :source="terms" />
				</div>
			</div>
		</div>
	</AppLayout>
</template>
